---
- hosts: linux
  become: true
  tasks:
  - name: docker_login
    docker_login:
              username: ajithengg13
              password: Ajithkumar@1314
  - name: pull 
    docker_image:
            name: ajithengg13/projectajith1:{{imagename}}

  - name: create container
    docker_container:
            name: web
            image: ajithengg13/projectajith1:{{imagename}}
            state: started
            ports:
                    "80:8080"
            tty: true
            detach: true
