#!/bin/sh

Ip=$(echo `az vm list-ip-addresses -g jenkins-rg -n dock |head -7 |tail -1 |cut -c 12-19`)
echo "$Ip"

echo "\n [linux] " >> /etc/ansible/hosts
echo "\n $Ip " >> /etc/ansible/hosts
echo "\n [linux:vars] " >> /etc/ansible/hosts
echo "ansible_connection=ssh" >> /etc/ansible/hosts
echo "ansible_user=vmadmin" >> /etc/ansible/hosts
echo "ansible_ssh_password=Ajithkumar@1314" >> /etc/ansible/hosts

