#!/bin/sh

Ip=$(echo `az vm list-ip-addresses -g jenkins-rg -n dock |head -7 |tail -1 |cut -c 12-19`)
echo "$Ip"

echo "\n [linux] " >> /etc/ansible/hosts
echo "\n $Ip " >> /etc/ansible/hosts
echo "\n [linux:vars] " >> /etc/ansible/hosts
echo "\n ansible_connection=ssh" >> /etc/ansible/hosts
echo "\n ansible_user=vmadmin" >> /etc/ansible/hosts
echo "\n ansible_ssh_pass=AjithKumar@1314" >> /etc/ansible/hosts

